# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW0gHkMdfOi9qTdCioEgIkctNvXwehT9
"""

# Install necessary packages
!pip install pandas scikit-learn

# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Create a larger synthetic dataset
data = {
    'Fever': [1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0],
    'Cough': [1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1],
    'Fatigue': [1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0],
    'Headache': [1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0],
    'Disease': ['Flu', 'Cold', 'Allergy', 'Migraine', 'Flu', 'Cold', 'Flu', 'Migraine', 'Allergy', 'Cold',
                'Flu', 'Cold', 'Allergy', 'Migraine', 'Flu', 'Cold', 'Flu', 'Migraine', 'Allergy', 'Cold']
}

df = pd.DataFrame(data)

# Encode the target variable
df['Disease'] = df['Disease'].astype('category')
disease_mapping = dict(enumerate(df['Disease'].cat.categories))
df['Disease'] = df['Disease'].cat.codes

# Split the data into features and target
X = df.drop('Disease', axis=1)
y = df['Disease']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Decision Tree classifier
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test, y_pred):.2f}')

# Function to predict disease based on input symptoms
def predict_disease(symptoms):
    symptoms_df = pd.DataFrame([symptoms])
    prediction = model.predict(symptoms_df)
    disease = disease_mapping[prediction[0]]
    return disease

# Example input
input_symptoms = {
    'Fever': 0,
    'Cough': 0,
    'Fatigue': 0,
    'Headache': 1
}

predicted_disease = predict_disease(input_symptoms)
print(f'The predicted disease is: {predicted_disease}')